name: app_flutter_hp
description: Proyecto segundo parcial Universidad.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  get: ^4.6.5
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/icon.png"
  adaptive_icon_background: "images/icon.png"
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true


  assets:
    - images/
